# Spring Boot configuration
spring:
  profiles:
    active: dev
# Database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gae?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      minimum-idle: 20
      maximum-pool-size: 50
      idle-timeout: 10000
      connection-test-query: "SELECT 1"
# JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
#Timestamp configuration
    properties:
      hibernate:
        jdbc:
          time_zone: "UTC"
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    time-zone: "UTC"